In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [11]:
df=pd.read_csv('food_safety.csv')
df

,product_type,packaging_type,shelf_life_days,storage_temperature_C,humidity_level_percent,moisture_content,preservative_level,pH_level,inspection_score_0_100,customer_rating_1_5,product_approval
0,Frozen Food,Paper,345,3.8,44.6,30.1,2.76,6.16,83,4,Approved
1,Canned Food,Vacuum Pack,264,1.2,50.5,19.3,1.99,6.48,83,5,Approved
2,Snacks,Metal,125,0.7,40.9,30.0,5.48,6.51,95,3,Approved
3,Dairy,Plastic,189,0.9,63.3,19.5,4.76,5.21,97,5,Approved
4,Snacks,Paper,44,0.5,67.4,7.3,4.03,5.15,97,5,Approved
...,...,...,...,...,...,...,...,...,...,...,...
495,Bakery,Glass,67,15.6,92.4,35.8,2.01,3.51,48,1,Rejected
496,Ready-to-Eat,Paper,117,24.3,89.8,64.9,1.97,3.36,42,2,Rejected
497,Juice,Plastic,100,11.3,87.1,45.7,2.68,3.69,42,1,Rejected
498,Ready-to-Eat,Vacuum Pack,23,14.7,89.5,48.1,0.15,3.12,41,3,Rejected
499,Snacks,Vacuum Pack,12,16.0,60.7,31.4,2.73,3.02,47,2,Rejected

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_type            500 non-null    str
 1   packaging_type          500 non-null    str
 2   shelf_life_days         500 non-null    int64
 3   storage_temperature_C   500 non-null    float64
 4   humidity_level_percent  500 non-null    float64
 5   moisture_content        500 non-null    float64
 6   preservative_level      500 non-null    float64
 7   pH_level                500 non-null    float64
 8   inspection_score_0_100  500 non-null    int64
 9   customer_rating_1_5     500 non-null    int64
 10  product_approval        500 non-null    str
dtypes: float64(5), int64(3), str(3)
memory usage: 54.5 KB

In [13]:
df.isnull().sum()

product_type              0
packaging_type            0
shelf_life_days           0
storage_temperature_C     0
humidity_level_percent    0
moisture_content          0
preservative_level        0
pH_level                  0
inspection_score_0_100    0
customer_rating_1_5       0
product_approval          0
dtype: int64

In [14]:
df=pd.get_dummies(df,columns=["product_type"],drop_first=True)
df=pd.get_dummies(df,columns=["packaging_type"],drop_first=True)
df

,shelf_life_days,storage_temperature_C,humidity_level_percent,moisture_content,preservative_level,pH_level,inspection_score_0_100,customer_rating_1_5,product_approval,product_type_Canned Food,product_type_Dairy,product_type_Frozen Food,product_type_Juice,product_type_Ready-to-Eat,product_type_Snacks,packaging_type_Metal,packaging_type_Paper,packaging_type_Plastic,packaging_type_Tetra Pack,packaging_type_Vacuum Pack
0,345,3.8,44.6,30.1,2.76,6.16,83,4,Approved,False,False,True,False,False,False,False,True,False,False,False
1,264,1.2,50.5,19.3,1.99,6.48,83,5,Approved,True,False,False,False,False,False,False,False,False,False,True
2,125,0.7,40.9,30.0,5.48,6.51,95,3,Approved,False,False,False,False,False,True,True,False,False,False,False
3,189,0.9,63.3,19.5,4.76,5.21,97,5,Approved,False,True,False,False,False,False,False,False,True,False,False
4,44,0.5,67.4,7.3,4.03,5.15,97,5,Approved,False,False,False,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,67,15.6,92.4,35.8,2.01,3.51,48,1,Rejected,False,False,False,False,False,False,False,False,False,False,False
496,117,24.3,89.8,64.9,1.97,3.36,42,2,Rejected,False,False,False,False,True,False,False,True,False,False,False
497,100,11.3,87.1,45.7,2.68,3.69,42,1,Rejected,False,False,False,True,False,False,False,False,True,False,False
498,23,14.7,89.5,48.1,0.15,3.12,41,3,Rejected,False,False,False,False,True,False,False,False,False,False,True
499,12,16.0,60.7,31.4,2.73,3.02,47,2,Rejected,False,False,False,False,False,True,False,False,False,False,True

In [15]:
df['product_approval'].value_counts()
df["product_approval"]=df["product_approval"].map({"Approved":1,"Rejected":0})
df.head()

,shelf_life_days,storage_temperature_C,humidity_level_percent,moisture_content,preservative_level,pH_level,inspection_score_0_100,customer_rating_1_5,product_approval,product_type_Canned Food,product_type_Dairy,product_type_Frozen Food,product_type_Juice,product_type_Ready-to-Eat,product_type_Snacks,packaging_type_Metal,packaging_type_Paper,packaging_type_Plastic,packaging_type_Tetra Pack,packaging_type_Vacuum Pack
0,345,3.8,44.6,30.1,2.76,6.16,83,4,1,False,False,True,False,False,False,False,True,False,False,False
1,264,1.2,50.5,19.3,1.99,6.48,83,5,1,True,False,False,False,False,False,False,False,False,False,True
2,125,0.7,40.9,30.0,5.48,6.51,95,3,1,False,False,False,False,False,True,True,False,False,False,False
3,189,0.9,63.3,19.5,4.76,5.21,97,5,1,False,True,False,False,False,False,False,False,True,False,False
4,44,0.5,67.4,7.3,4.03,5.15,97,5,1,False,False,False,False,False,True,False,True,False,False,False

In [16]:
x=df.drop("product_approval",axis=1)
y=df["product_approval"]
x

,shelf_life_days,storage_temperature_C,humidity_level_percent,moisture_content,preservative_level,pH_level,inspection_score_0_100,customer_rating_1_5,product_type_Canned Food,product_type_Dairy,product_type_Frozen Food,product_type_Juice,product_type_Ready-to-Eat,product_type_Snacks,packaging_type_Metal,packaging_type_Paper,packaging_type_Plastic,packaging_type_Tetra Pack,packaging_type_Vacuum Pack
0,345,3.8,44.6,30.1,2.76,6.16,83,4,False,False,True,False,False,False,False,True,False,False,False
1,264,1.2,50.5,19.3,1.99,6.48,83,5,True,False,False,False,False,False,False,False,False,False,True
2,125,0.7,40.9,30.0,5.48,6.51,95,3,False,False,False,False,False,True,True,False,False,False,False
3,189,0.9,63.3,19.5,4.76,5.21,97,5,False,True,False,False,False,False,False,False,True,False,False
4,44,0.5,67.4,7.3,4.03,5.15,97,5,False,False,False,False,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,67,15.6,92.4,35.8,2.01,3.51,48,1,False,False,False,False,False,False,False,False,False,False,False
496,117,24.3,89.8,64.9,1.97,3.36,42,2,False,False,False,False,True,False,False,True,False,False,False
497,100,11.3,87.1,45.7,2.68,3.69,42,1,False,False,False,True,False,False,False,False,True,False,False
498,23,14.7,89.5,48.1,0.15,3.12,41,3,False,False,False,False,True,False,False,False,False,False,True
499,12,16.0,60.7,31.4,2.73,3.02,47,2,False,False,False,False,False,True,False,False,False,False,True

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [18]:
scaler=MinMaxScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_sclaled=scaler.transform(x_test)

In [19]:
x_train_scaled=pd.DataFrame(x_train_scaled,columns=x_train.columns)
x_test_sclaled=pd.DataFrame(x_test_sclaled,columns=x_test.columns)

In [20]:
models = {
"Logistic Regression": LogisticRegression(max_iter=1000),
"Naive Bayes": GaussianNB(),
"Decision Tree": DecisionTreeClassifier(random_state=42),
"Random Forest": RandomForestClassifier(random_state=42)
}
models

{'Logistic Regression': LogisticRegression(max_iter=1000),
 'Naive Bayes': GaussianNB(),
 'Decision Tree': DecisionTreeClassifier(random_state=42),
 'Random Forest': RandomForestClassifier(random_state=42)}

In [ ]:
results={}
for name,model in models.items():
    print(f"\n====={name}=====")
    if name in ["Logistic Regression","Naive Bayes"]:
                model.fit(x_train_scaled,y_train)
                y_pred=model.predict(x_test_sclaled)  
    else:
        model.fit(x_train,y_train)
        y_pred=model.predict(x_test)

    acc=accuracy_score(y_test,y_pred)
    pre=precision_score(y_test,y_pred)
    rec=recall_score(y_test,y_pred)
    f1=f1_score(y_test,y_pred)
    results[name]=[acc,pre,rec,f1]
    print("Accuracy:",acc)
    print("precision",pre)
    print("recall",rec)
    print("f1score",f1)
    #results_df=pd.DataFrame(results,index=["Accuracy","precision","recall","f1_score"]).T
    results_df = pd.DataFrame(
    results, 
    index=["Accuracy", "Precision", "Recall", "F1_Score"]
).T
    results_df

=====Logistic Regression=====
Accuracy: 1.0
precision 1.0
recall 1.0
f1score 1.0

=====Naive Bayes=====
Accuracy: 1.0
precision 1.0
recall 1.0
f1score 1.0

=====Decision Tree=====
Accuracy: 1.0
precision 1.0
recall 1.0
f1score 1.0

=====Random Forest=====
Accuracy: 1.0
precision 1.0
recall 1.0
f1score 1.0

In [23]:
# Checking best ML model for the data
best_model_name = results_df["recall"].idxmax()
print("Best model based on Recall:", best_model_name)
best_model = models[best_model_name]

if best_model_name in ["Logistic Regression", "Naive Bayes"]:
    best_model.fit(x_train_scaled, y_train)
else:
    best_model.fit(x_train, y_train)

# Saving the model
with open("model.pkl", "wb") as f:
    pickle.dump(best_model, f)

# Saving the scaler
if best_model_name in ["Logistic Regression", "Naive Bayes"]:
    with open("scaler.pkl", "wb") as f:
        pickle.dump(scaler, f)

Best model based on Recall: Logistic Regression